# -*- coding: utf-8 -*-
#T. Lemberger, 2018

NBITS = 32 # number of bits to encode characters; not very useful since making converter flexible slows it down
DATA_DIR = "data" # directory for datasets used for training and testing
MODEL_DIR = "models" # directory where new models are saved by train.meta
PROD_DIR = "rack" # directory for 'production' models loaded by predict.engine
RUNS_LOG_DIR = "runs" # directory to store plots generated by tensorboard
MARKING_CHAR = u'\u0000' # special character used to anonymize an entity before learning context-dependent features
MARKING_CHAR_ORD = ord(MARKING_CHAR)
MIN_PADDING = 20 # the number of (usually space) characters added to each example as padding to mitigate 'border effects' in learning
MIN_SIZE = 140 # input needs to be of minimal size to survive successive convergent convolutions; ideally, should be calculated analytically
